<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.OpenIdConnectServer" />
    <PackageReference Include="AspNetCore.HealthChecks.Oracle" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" />
  </ItemGroup>
</Project>
