<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <RootNamespace>Rms.Risk.Mango.Pivot.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
    
</Project>
